-- PayCore-KR 초기 스키마 (docs/payment-platform-design.md §6)
-- 원칙: 멱등성의 최종 방어선은 코드가 아니라 UNIQUE 제약이다.
--      금액은 KRW 정수(NUMBER(18,0)) — 부동소수점 금지.
--      시각 컬럼은 TIMESTAMP WITH TIME ZONE — 오프셋을 컬럼이 스스로 설명한다 (docs/adr/0005).
--      단, RECON_DATE 는 시점이 아니라 '업무일자'라서 DATE 를 유지한다.

CREATE TABLE PAYMENT (
    PAYMENT_ID        VARCHAR2(26)  PRIMARY KEY,          -- ULID
    IDEMPOTENCY_KEY   VARCHAR2(64)  NOT NULL,
    END_TO_END_ID     VARCHAR2(35)  NOT NULL,
    DEBTOR_ACCOUNT    VARCHAR2(32)  NOT NULL,
    CREDITOR_ACCOUNT  VARCHAR2(32)  NOT NULL,
    CREDITOR_BANK     VARCHAR2(3)   NOT NULL,
    AMOUNT            NUMBER(18,0)  NOT NULL,
    CURRENCY          CHAR(3)       DEFAULT 'KRW' NOT NULL,
    REMITTANCE_INFO   VARCHAR2(140),
    STATUS            VARCHAR2(20)  NOT NULL,
    VERSION           NUMBER(10)    DEFAULT 0 NOT NULL,   -- 낙관적 락
    FIRST_RESPONSE    CLOB,                               -- 멱등 응답 재생용
    CREATED_AT        TIMESTAMP WITH TIME ZONE     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP WITH TIME ZONE     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_PAYMENT_AMOUNT CHECK (AMOUNT > 0),
    CONSTRAINT UQ_PAYMENT_IDEM   UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT UQ_PAYMENT_E2E    UNIQUE (END_TO_END_ID)
);

CREATE INDEX IX_PAYMENT_STATUS ON PAYMENT (STATUS, CREATED_AT);

CREATE TABLE PAYMENT_STATUS_HISTORY (
    ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PAYMENT_ID   VARCHAR2(26)  NOT NULL,
    FROM_STATUS  VARCHAR2(20),
    TO_STATUS    VARCHAR2(20)  NOT NULL,
    TRIGGERED_BY VARCHAR2(100) NOT NULL,   -- 메시지ID / 운영자ID
    REASON       VARCHAR2(400),
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_HIST_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (PAYMENT_ID)
);

CREATE INDEX IX_HIST_PAYMENT ON PAYMENT_STATUS_HISTORY (PAYMENT_ID, CREATED_AT);

CREATE TABLE OUTBOX_EVENT (
    EVENT_ID      VARCHAR2(26) PRIMARY KEY,
    AGGREGATE_ID  VARCHAR2(26) NOT NULL,                  -- paymentId = Kafka 파티션 키
    EVENT_TYPE    VARCHAR2(50) NOT NULL,
    PAYLOAD       CLOB         NOT NULL,
    STATUS        VARCHAR2(10) DEFAULT 'NEW' NOT NULL,
    ATTEMPTS      NUMBER(5)    DEFAULT 0 NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE    DEFAULT SYSTIMESTAMP NOT NULL,
    PUBLISHED_AT  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT CK_OUTBOX_STATUS CHECK (STATUS IN ('NEW', 'PUBLISHED'))
);

CREATE INDEX IX_OUTBOX_NEW ON OUTBOX_EVENT (STATUS, CREATED_AT);

-- 소비자 멱등성 (inbox 패턴, docs §7.2)
CREATE TABLE PROCESSED_MESSAGE (
    CONSUMER_GROUP VARCHAR2(50)  NOT NULL,
    MESSAGE_ID     VARCHAR2(64)  NOT NULL,
    PROCESSED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PROCESSED PRIMARY KEY (CONSUMER_GROUP, MESSAGE_ID)
);

CREATE TABLE CLEARING_MESSAGE_LOG (
    MSG_ID        VARCHAR2(36) PRIMARY KEY,               -- UETR 역할
    PAYMENT_ID    VARCHAR2(26) NOT NULL,
    END_TO_END_ID VARCHAR2(35) NOT NULL,
    MSG_TYPE      VARCHAR2(10) NOT NULL,                  -- pacs.008 / pacs.002 / pacs.028
    DIRECTION     VARCHAR2(3)  NOT NULL,                  -- OUT / IN
    PAYLOAD       CLOB         NOT NULL,
    SENT_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_CLR_DIRECTION CHECK (DIRECTION IN ('OUT', 'IN')),
    CONSTRAINT FK_CLR_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (PAYMENT_ID)
);

CREATE INDEX IX_CLR_E2E ON CLEARING_MESSAGE_LOG (END_TO_END_ID, SENT_AT);

CREATE TABLE JOURNAL (
    JOURNAL_ID  VARCHAR2(26) PRIMARY KEY,
    PAYMENT_ID  VARCHAR2(26) NOT NULL,
    POSTED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_JOURNAL_PAYMENT UNIQUE (PAYMENT_ID)     -- 원장 멱등성
);

CREATE TABLE LEDGER_ENTRY (
    ENTRY_ID    VARCHAR2(26) PRIMARY KEY,
    JOURNAL_ID  VARCHAR2(26) NOT NULL,
    ACCOUNT_ID  VARCHAR2(32) NOT NULL,
    DR_CR       CHAR(1)      NOT NULL,
    AMOUNT      NUMBER(18,0) NOT NULL,
    CONSTRAINT CK_ENTRY_DRCR   CHECK (DR_CR IN ('D', 'C')),
    CONSTRAINT CK_ENTRY_AMOUNT CHECK (AMOUNT > 0),
    CONSTRAINT FK_ENTRY_JOURNAL FOREIGN KEY (JOURNAL_ID) REFERENCES JOURNAL (JOURNAL_ID)
);

CREATE INDEX IX_ENTRY_JOURNAL ON LEDGER_ENTRY (JOURNAL_ID);
CREATE INDEX IX_ENTRY_ACCOUNT ON LEDGER_ENTRY (ACCOUNT_ID);

CREATE TABLE RECON_BREAK (
    BREAK_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RECON_DATE  DATE          NOT NULL,
    PAYMENT_ID  VARCHAR2(26),
    BREAK_TYPE  VARCHAR2(30)  NOT NULL,
    DETAIL      VARCHAR2(1000),
    STATUS      VARCHAR2(10)  DEFAULT 'OPEN' NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_BREAK_STATUS CHECK (STATUS IN ('OPEN', 'RESOLVED'))
);

CREATE INDEX IX_BREAK_DATE ON RECON_BREAK (RECON_DATE, STATUS);
