-- 일일 이체 한도 (docs §5.2)
-- 비관적 락(SELECT ... FOR UPDATE)으로 차감한다. 근거는 docs/adr/0006 참고.
CREATE TABLE DAILY_LIMIT (
    ACCOUNT_ID   VARCHAR2(32)  NOT NULL,
    LIMIT_DATE   DATE          NOT NULL,          -- 업무일자(KST). 시점이 아니라 날짜다.
    LIMIT_AMOUNT NUMBER(18,0)  NOT NULL,
    USED_AMOUNT  NUMBER(18,0)  DEFAULT 0 NOT NULL,
    UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DAILY_LIMIT PRIMARY KEY (ACCOUNT_ID, LIMIT_DATE),
    CONSTRAINT CK_DAILY_LIMIT_RANGE CHECK (USED_AMOUNT >= 0 AND USED_AMOUNT <= LIMIT_AMOUNT)
);

-- 비즈니스 중복 의심 판정(동일 debtor/creditor/amount 5분 내 재접수) 조회를 받쳐주는 인덱스.
CREATE INDEX IX_PAYMENT_DUP_CHECK ON PAYMENT (DEBTOR_ACCOUNT, CREDITOR_ACCOUNT, AMOUNT, CREATED_AT);
