-- 운영 개입 기록과 DLT 워크리스트 (docs §7.5, §5.7)
--
-- 두 테이블의 존재 이유는 같다: 자동화가 손을 뗀 지점에서 사람이 무엇을 했는지 남기는 것.
-- 결제 시스템에서 "누가 언제 왜 이 건을 성공으로 바꿨는가"는 상태 자체만큼 중요하다.

CREATE TABLE OPERATION_AUDIT (
    AUDIT_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACTOR       VARCHAR2(64)   NOT NULL,          -- 운영자 식별자 (X-Operator 헤더)
    ACTION      VARCHAR2(40)   NOT NULL,          -- REPAIR_PAYMENT / REPUBLISH_DEAD_LETTER ...
    TARGET_TYPE VARCHAR2(20)   NOT NULL,          -- PAYMENT / DEAD_LETTER
    TARGET_ID   VARCHAR2(64)   NOT NULL,
    DETAIL      VARCHAR2(1000 CHAR),              -- 사유. 한글이 들어가므로 문자 기준 길이다(V3 참고).
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IX_AUDIT_TARGET ON OPERATION_AUDIT (TARGET_TYPE, TARGET_ID, CREATED_AT);
CREATE INDEX IX_AUDIT_CREATED ON OPERATION_AUDIT (CREATED_AT);

-- DLT 로 밀려난 메시지. 토픽에만 두면 운영자가 볼 수 없고, 재발행 이력도 남길 곳이 없다.
CREATE TABLE DEAD_LETTER (
    DEAD_LETTER_ID   VARCHAR2(26)  PRIMARY KEY,
    ORIGINAL_TOPIC   VARCHAR2(100) NOT NULL,
    ORIGINAL_PARTITION NUMBER(5),
    ORIGINAL_OFFSET  NUMBER(19),
    MESSAGE_KEY      VARCHAR2(64),
    EVENT_ID         VARCHAR2(26),
    EVENT_TYPE       VARCHAR2(50),
    PAYLOAD          CLOB          NOT NULL,
    EXCEPTION_TYPE   VARCHAR2(200),
    EXCEPTION_MESSAGE VARCHAR2(1000 CHAR),
    STATUS           VARCHAR2(12)  DEFAULT 'NEW' NOT NULL,   -- NEW / REPUBLISHED / DISCARDED
    RECEIVED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    RESOLVED_AT      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT CK_DEAD_LETTER_STATUS CHECK (STATUS IN ('NEW', 'REPUBLISHED', 'DISCARDED')),
    -- 같은 레코드가 두 번 밀려나도 워크리스트에는 한 줄이다.
    CONSTRAINT UQ_DEAD_LETTER_ORIGIN UNIQUE (ORIGINAL_TOPIC, ORIGINAL_PARTITION, ORIGINAL_OFFSET)
);

CREATE INDEX IX_DEAD_LETTER_STATUS ON DEAD_LETTER (STATUS, RECEIVED_AT);
